src/FS/TrainingProgramsBundle/Entity/EmployeeTrainingState.php
<?php
/**
 * Created by PhpStorm.
 * User: Vladislav
 * Date: 21.10.2016
 * Time: 18:30
 * Autor: <vladislav@fora-soft.com>
 */

namespace FS\TrainingProgramsBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * Class EmployeeTrainingState
 * @package FS\TrainingProgramsBundle\Entity
 * @author <vladislav@fora-soft.com>
 *
 * @ORM\Table(name="employee_training_state")
 * @ORM\Entity(repositoryClass="FS\TrainingProgramsBundle\Entity\Repository\EmployeeTrainingStateRepository")
 */
class EmployeeTrainingState
{

    const  TIME_STATUS__NO_TIME = 'no_time';
    const  TIME_STATUS__TIMER = 'timer';

    const FINAL_STATUS_PASSED = 'passed';
    const FINAL_STATUS_FAILED = 'failed';
    const FINAL_STATUS_IN_PROGRESS = 'in_progress';


    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     *
     */
    protected $id;


    /**
     * @var Access
     *
     * @ORM\OneToOne(targetEntity="FS\TrainingProgramsBundle\Entity\Access", inversedBy="trainingState")
     * @ORM\JoinColumn(name="training_access_id", referencedColumnName="id")
     */
    protected $access;


    /**
     * @var TrainingProgram
     * @ORM\ManyToOne(targetEntity="FS\TrainingProgramsBundle\Entity\TrainingProgram")
     * @ORM\JoinColumn(name="tp_id", referencedColumnName="id")
     */
    protected $training;

    /**
     * @var integer
     *  slide id
     *
     * @ORM\Column(type="integer")
     */
    protected $currentSlide = 0;


    /**
     * @var integer
     *
     * next slide id
     *
     * @ORM\Column(type="integer")
     */
    protected $nextSlide = 0;


    /**
     * @var string
     * @ORM\Column(type="string")
     */
    protected $timeStatus = self::TIME_STATUS__NO_TIME;


    /**
     * @var integer
     *
     * @ORM\Column(type="integer")
     */
    protected $timeRemaining = 0;


    /**
     * @var \DateTime
     *
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $startTimer;

    /**
     * @var \DateTime
     *
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $endTimer;

    /**
     * @var bool
     *
     * @ORM\Column(type="boolean")
     */
    protected $paused = false;


    /**
     * @var \DateTime
     *
     * @ORM\Column(type="datetime", nullable=true)
     */
    protected $pauseStart;


    /**
     * @var integer
     *
     * @ORM\Column(type="integer", options={"default":0})
     */
    protected $remainTimePause = 0;


    /**
     * Status of presentation
     */

    /**
     * @var string
     * @ORM\Column(type="string")
     */
    protected $passedStatus = self::FINAL_STATUS_IN_PROGRESS;

    /**
     * @var \DateTime
     * @ORM\Column(type="datetime", nullable=true);
     */
    protected $endTime;

    /**
     * @var integer
     * @ORM\Column(type="integer")
     */
    protected $timeOffset = 0;

    /**
     * @var float
     * @ORM\Column(type="float")
     */
    protected $ratio = 0.0;

    /**
     * @var string
     * @ORM\Column(type="string", length=8, nullable=true)
     */
    protected $certificateId = null;
    /**
     * @var \DateTime
     * @ORM\Column(name="valid_until", nullable=true, type="datetime")
     */
    protected $validUntil = null;

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return TrainingProgram
     */
    public function getTraining()
    {
        return $this->training;
    }

    /**
     * @param TrainingProgram $training
     */
    public function setTraining($training)
    {
        $this->training = $training;
    }

    /**
     * @return integer
     */
    public function getCurrentSlide()
    {
        return $this->currentSlide;
    }

    /**
     * @param integer $currentSlide
     */
    public function setCurrentSlide($currentSlide)
    {
        $this->currentSlide = $currentSlide;
    }

    /**
     * @return integer
     */
    public function getNextSlide()
    {
        return $this->nextSlide;
    }

    /**
     * @param integer $nextSlide
     */
    public function setNextSlide($nextSlide)
    {
        $this->nextSlide = $nextSlide;
    }

    /**
     * @return string
     */
    public function getTimeStatus()
    {
        return $this->timeStatus;
    }

    /**
     * @param string $timeStatus
     */
    public function setTimeStatus($timeStatus)
    {
        $this->timeStatus = $timeStatus;
    }

    /**
     * @return int
     */
    public function getTimeRemaining()
    {
        return $this->timeRemaining;
    }

    /**
     * @param int $timeRemaining
     */
    public function setTimeRemaining($timeRemaining)
    {
        $this->timeRemaining = $timeRemaining;
    }

    /**
     * @return \DateTime
     */
    public function getStartTimer()
    {
        return $this->startTimer;
    }

    /**
     * @param \DateTime $startTimer
     */
    public function setStartTimer($startTimer)
    {
        $this->startTimer = $startTimer;
    }

    /**
     * @return \DateTime
     */
    public function getEndTimer()
    {
        return $this->endTimer;
    }

    /**
     * @param \DateTime $endTimer
     */
    public function setEndTimer($endTimer)
    {
        $this->endTimer = $endTimer;
    }

    /**
     * Get paused
     *
     * @return boolean
     */
    public function getPaused()
    {
        return $this->paused;
    }

    /**
     * @param boolean $paused
     */
    public function setPaused($paused)
    {
        $this->paused = $paused;
    }

    /**
     * Get access
     *
     * @return Access
     */
    public function getAccess()
    {
        return $this->access;
    }

    /**
     * Set access
     *
     * @param Access $access
     *
     * @return EmployeeTrainingState
     */
    public function setAccess(Access $access = null)
    {
        $this->access = $access;

        return $this;
    }

    /**
     * @return string
     */
    public function getPassedStatus()
    {
        return $this->passedStatus;
    }

    /**
     * @param string $passedStatus
     */
    public function setPassedStatus($passedStatus)
    {
        $this->passedStatus = $passedStatus;
    }

    /**
     * @return \DateTime
     */
    public function getEndTime()
    {
        return $this->endTime;
    }

    /**
     * @param \DateTime $endTime
     */
    public function setEndTime($endTime)
    {
        $this->endTime = $endTime;
    }

    /**
     * @return int
     */
    public function getTimeOffset()
    {
        return $this->timeOffset;
    }

    /**
     * @param int $timeOffset
     */
    public function setTimeOffset($timeOffset)
    {
        $this->timeOffset = $timeOffset;
    }

    /**
     * @return float
     */
    public function getRatio()
    {
        return $this->ratio;
    }

    /**
     * @param float $ratio
     */
    public function setRatio($ratio)
    {
        $this->ratio = $ratio;
    }

    public function isPassed()
    {
        return $this->passedStatus === self::FINAL_STATUS_PASSED;
    }

    /**
     * @return \DateTime
     */
    public function getPauseStart()
    {
        return $this->pauseStart;
    }

    /**
     * @param \DateTime $pauseStart
     */
    public function setPauseStart($pauseStart)
    {
        $this->pauseStart = $pauseStart;
    }

    /**
     * @return int
     */
    public function getRemainTimePause()
    {
        return $this->remainTimePause;
    }

    /**
     * @param int $remainTimePause
     */
    public function setRemainTimePause($remainTimePause)
    {
        $this->remainTimePause = $remainTimePause;
    }

    /**
     * @return string
     */
    public function getTitle()
    {
        return $this->getTraining()->getTitle();
    }

    /**
     * @return string
     */
    public function getCertificateId()
    {
        return $this->certificateId;
    }

    /**
     * @param string $certificateId
     * @return EmployeeTrainingState
     */
    public function setCertificateId($certificateId)
    {
        $this->certificateId = $certificateId;
        return $this;
    }

    /**
     * @return EmployeeTrainingState
     */
    public function generateCertificateId()
    {
        $this->certificateId = substr(md5(uniqid("certificate")), 0, 8);
        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getValidUntil()
    {
        return $this->validUntil;
    }

    /**
     * @param \DateTime $validUntil
     * @return EmployeeTrainingState
     */
    public function setValidUntil($validUntil)
    {
        $this->validUntil = $validUntil;
        return $this;
    }

    public function fillValidUntil()
    {
        $months = $this->getTraining()->getCertificateValidMonths();
        $validUntil = $this->getTraining()->getCertificateValidUntil();
        if ($months > 0) {
            $validUntil = clone $this->getEndTime();
            $this->validUntil = $validUntil->modify("+$months month");
        } else if (!empty($validUntil)) {
            $this->validUntil = $validUntil;
        } else {
            $validUntil = clone $this->getEndTime();
            $this->validUntil = $validUntil->modify("+2 year");
        }
    }
}

src/FS/TrainingProgramsBundle/Entity/Payment.php
<?php

namespace FS\TrainingProgramsBundle\Entity;


use Doctrine\ORM\Mapping as ORM;


/**
 * @ORM\Table(name="payments")
 * @ORM\Entity(repositoryClass="FS\TrainingProgramsBundle\Entity\Repository\PaymentsRepository")
 */
class Payment
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\ManyToOne(targetEntity="FS\UserBundle\Entity\User")
     * @ORM\JoinColumn(name="user_id", referencedColumnName="id", onDelete="SET NULL")
     */
    protected $user;

    /**
     * @ORM\ManyToOne(targetEntity="FS\TrainingProgramsBundle\Entity\TrainingProgram")
     * @ORM\JoinColumn(name="training_program_id", referencedColumnName="id", onDelete="SET NULL")
     */
    protected $trainingProgram;

    /**
     * @ORM\Column(type="date")
     */
    protected $date;

    /**
     * @ORM\Column(type="float")
     */
    protected $totalPrice;

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set date
     *
     * @param \DateTime $date
     *
     * @return Payment
     */
    public function setDate($date)
    {
        $this->date = $date;

        return $this;
    }

    /**
     * Set current date
     *
     * @return Payment
     */
    public function setCurrentDate()
    {
        $this->date = new \DateTime();

        return $this;
    }

    /**
     * Get date
     *
     * @return \DateTime
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     * Set totalPrice
     *
     * @param float $totalPrice
     *
     * @return Payment
     */
    public function setTotalPrice($totalPrice)
    {
        $this->totalPrice = $totalPrice;

        return $this;
    }

    /**
     * Get totalPrice
     *
     * @return float
     */
    public function getTotalPrice()
    {
        return $this->totalPrice;
    }

    /**
     * Set user
     *
     * @param \FS\UserBundle\Entity\User $user
     *
     * @return Payment
     */
    public function setUser(\FS\UserBundle\Entity\User $user = null)
    {
        $this->user = $user;

        return $this;
    }

    /**
     * Get user
     *
     * @return \FS\UserBundle\Entity\User
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Set trainingProgram
     *
     * @param \FS\TrainingProgramsBundle\Entity\TrainingProgram $trainingProgram
     *
     * @return Payment
     */
    public function setTrainingProgram(\FS\TrainingProgramsBundle\Entity\TrainingProgram $trainingProgram = null)
    {
        $this->trainingProgram = $trainingProgram;

        return $this;
    }

    /**
     * Get trainingProgram
     *
     * @return \FS\TrainingProgramsBundle\Entity\TrainingProgram
     */
    public function getTrainingProgram()
    {
        return $this->trainingProgram;
    }
}

src/FS/TrainingProgramsBundle/Controller/PaymentsController.php
<?php

namespace FS\TrainingProgramsBundle\Controller;


use FS\TrainingProgramsBundle\Entity\Access;
use FS\TrainingProgramsBundle\Entity\TrainingProgram;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Config\Definition\Exception\Exception;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Stripe\Stripe;
use Stripe\Customer;
use Stripe\Charge;


class PaymentsController extends Controller
{
    /**
     * @param Request $request
     * @return Response
     * @Route(path="/admin/payments" , name="payments")
     * @Template()
     */
    public function indexAction(Request $request)
    {
        $paymentsRaw = $this->getDoctrine()
            ->getRepository('FSTrainingProgramsBundle:Payment')
            ->getFindAllWithDeletedOrderedByDateRaw();
        $paymentsPagination = $this->get('knp_paginator')
            ->paginate($paymentsRaw, $request->query->get('page', 1), 30);

        $this->get('session')->set('training-return', $this->generateUrl('payments'));

        return $this->render('FSTrainingProgramsBundle:Payments:index.html.twig', [
            'paymentsPagination' => $paymentsPagination
        ]);
    }

    /**
     * @param Request $request
     * @param TrainingProgram $trainingProgram
     * @throws
     * @return Response
     * @Route(path="/training-programs/{link}/pay", name="pay_for_training")
     * @ParamConverter("trainingProgram", class="FSTrainingProgramsBundle:TrainingProgram")
     * @Security(
     *     expression="(is_granted('IS_AUTHENTICATED_REMEMBERED') || is_granted('IS_AUTHENTICATED_FULLY')) && (user.hasRole('ROLE_VENDOR') || user.hasRole('ROLE_EMPLOYEE'))"
     * )
     */
    public function payAction(Request $request, TrainingProgram $trainingProgram)
    {
        $token = $request->get('stripeToken');
        $amount = $request->get('amount') > 0 ? $request->get('amount') : 1;
        $paymentDone = false;

        if ($token) {
            $stripeService = $this->get('fs_training.util.stripe_service');
            
            if ($this->getUser()->hasRole('ROLE_VENDOR')) {
                $requestManager = $this->get('fs_training.model.manager.request_manager');
                $trainingRequest = $requestManager->getRequest($this->getUser(), $trainingProgram);
                $paymentDone = $stripeService->buyTrainingsAsVendor($this->getUser(), $trainingRequest, $token, $amount);
            } else {
                $accessManager = $this->get('fs_training.model.manager.access_manager');
                $trainingAccess = $accessManager->getAccess($this->getUser(), $trainingProgram);
                $paymentDone = $stripeService->buyTrainingAsEmployee($this->getUser(), $trainingAccess, $token);
            }
        }

        if ($request->isXmlHttpRequest()) {
            $responseJsonData = null;

            if ($paymentDone == false) {
                $responseJsonData = [
                    'status' => 'success',
                    'content' => $this->renderView('@FSTrainingPrograms/Payments/success.html.twig', [
                        'amount' => $amount
                    ])
                ];
            } elseif ($this->getUser()->hasRole('ROLE_VENDOR')) {
                $responseJsonData = [
                    'status' => 'success-vendor',
                    'content' => [
                        'trainingStatus' => $trainingRequest->getStatus(),
                        'modal' => $this->renderView('@FSTrainingPrograms/Payments/successVendor.html.twig', [
                            'amount' => $trainingRequest->getAmountOfTrainings()
                        ])
                    ]
                ];
            } else {
                $responseJsonData = [
                    'status' => 'success-employee',
                    'content' => [
                        'modal' => $this->renderView('@FSTrainingPrograms/Payments/successEmployee.twig'),
                        'row' => $this->renderView('@FSTrainingPrograms/Requests/employee/requestRow.html.twig', [
                            'trainingProgram' => $trainingProgram,
                            'access' => $trainingAccess,
                            'trainingState' => $trainingAccess->getTrainingState()
                        ]),
                        'trainingAction' => $this->renderView(
                            '@FSTrainingPrograms/TrainingPrograms/employee/trainingAction.html.twig',
                            [
                                'trainingProgram' => $trainingProgram,
                                'access' => $trainingAccess,
                            ]
                        )
                    ]
                ];
            }

            return new JsonResponse($responseJsonData);
        }

        return $this->redirectToRoute('show_training_program', [
            'link' => $trainingProgram->getLink()
        ]);
    }
}

src/FS/TrainingProgramsBundle/Resources/views/Payments/error.html.twig
<div class="modal-content">
    <div class="modal-header">
        <div class="row">
            <div class="col-sm-12 text-center">
                <h4>Payment Failed</h4>
            </div>
        </div>
    </div>

    <div class="modal-body">
        <p class="text-center">
            Something went wrong.
            <br>
        </p>
    </div>

    <div class="modal-footer">
        <div class="row text-center">
            <button class="btn btn-default" data-dismiss="modal">
                Close
            </button>
        </div>
    </div>
</div>

src/FS/TrainingProgramsBundle/Resources/views/Payments/index.html.twig
{% extends "base.html.twig" %}

{% block content %}
    <main>
        <div>
            {% if paymentsPagination is empty %}
                <p>No Payments</p>
            {% else %}
                <table class="table font-normal">
                    <thead>
                    <tr>
                        <th class="link-padding">User</th>
                        <th class="link-padding">Training</th>
                        <th>Date</th>
                        <th>Total Price</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for payment in paymentsPagination %}
                        <tr>
                            <td>
                                {% if payment.user %}
                                    {% if payment.user.hasRole('ROLE_VENDOR') %}
                                        {%  if payment.user.deletedAt %}
                                            <span class="text-danger link-padding">
                                                Vendor {{ payment.user.fullName }} (deleted)
                                            </span>
                                        {% else %}
                                            <a href="{{ path('index_vendor_profile', {'vendor': payment.user.id}) }}">
                                                Vendor {{ payment.user.fullName }}
                                            </a>
                                        {% endif %}
                                    {% else %}
                                        {%  if payment.user.deletedAt %}
                                            <span class="text-danger link-padding">
                                                Employee {{ payment.user.fullName }} (deleted)
                                            </span>
                                        {% else %}
                                            <a href="{{ path('index_employee_profile', {'employee': payment.user.id}) }}">
                                                Employee {{ payment.user.fullName }}
                                            </a>
                                        {% endif %}
                                    {% endif %}
                                {% else %}
                                    <span class="text-danger link-padding">
                                        User was deleted.
                                    </span>
                                {% endif %}
                            </td>
                            <td>
                                {% if payment.trainingProgram %}
                                    {% if payment.trainingProgram.deletedAt %}
                                        <span class="text-danger link-padding">
                                            {{ payment.trainingProgram.title|training_name_format|nl2br }}
                                        </span>
                                    {% else %}
                                        <a href="{{ path('show_training_program', {'link': payment.trainingProgram.link}) }}">
                                            {{ payment.trainingProgram.title|training_name_format|nl2br }}
                                        </a>
                                    {% endif %}
                                {% else %}
                                    <span class="text-danger link-padding">
                                        Training was deleted.
                                    </span>
                                {% endif %}
                            </td>
                            <td>
                                {{ payment.date | date('d M. Y') }}
                            </td>
                            <td>
                                ${{ payment.totalPrice }}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% endif %}
            <div class="text-center font-normal">
                {{ knp_pagination_render(paymentsPagination) }}
            </div>
        </div>
    </main>
{% endblock %}

src/FS/TrainingProgramsBundle/Resources/views/Payments/successEmployee.twig
<div class="modal-content">
    <div class="modal-header">
        <div class="row">
            <div class="col-sm-12 text-center">
                <h4>Successful Payment</h4>
            </div>
        </div>
    </div>

    <div class="modal-body">
        <p class="text-center">
            Now you can complete the training.
        </p>
    </div>

    <div class="modal-footer">
        <div class="row text-center">
            <button class="btn" data-dismiss="modal">
                Close
            </button>
        </div>
    </div>
</div>

src/FS/TrainingProgramsBundle/Resources/views/Payments/successVendor.html.twig
<div class="modal-content">
    <div class="modal-header">
        <div class="row">
            <div class="col-sm-12 text-center">
                <h4>Successful Payment</h4>
            </div>
        </div>
    </div>

    <div class="modal-body">
        <p class="text-center">
            Now you have {{ amount }} paid trainings.
            <br>
            The first {{ amount }} employees will be able to take training right away, others will need to pay for the training themselves.
        </p>
    </div>

    <div class="modal-footer">
        <div class="row text-center">
            <button class="btn" data-dismiss="modal">
                Close
            </button>
        </div>
    </div>
</div>